name: Publish Node Module
on: [push]
jobs:
  npm_publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v1
        with:
          node-version: "12.x"
          registry-url: 'registry-url: "https://npm.pkg.github.com/yazilim-vip"'
      - run: |
          yarn install
          yarn build
          yarn publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
